spring.application.name=dietplanner
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/smart_diet_planner

# Swagger / OpenAPI configurations
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
